### ISSUE TITLE
NonMatchingChecksumError when loading dataset in HuggingFace

### ISSUE THREAD

**Issue by constanzafierro** [nala-cub/coda#1]
Hello!

I'm getting the following error when trying to load the dataset in huggingface datasets
```
NonMatchingChecksumError: Checksums didn't match for dataset source files:
['https://huggingface.co/datasets/corypaik/coda/resolve/main/data/default_train.jsonl', 'https://huggingface.co/datasets/corypaik/coda/resolve/main/data/default_validation.jsonl', 'https://huggingface.co/datasets/corypaik/coda/resolve/main/data/default_test.jsonl']
```
Colab to reproduce: https://colab.research.google.com/drive/1FRxDKyW4E6XUxYTCzGKKbvsCTHGK2KAO?usp=sharing

Is this expected?

Thanks!

**Comment by corypaik** [comment]
Hi, thanks for pointing this out, that shouldn't be happening! I did some digging, and it looks like the checksums were just incorrect. I pushed a fix for it, so you should be able to use it now. I think this auto-closed when I pushed the fix, but feel free to reopen it if you have any problems with downloading the dataset. 

As for what went wrong with the checksums, I have no clue. I tried rewinding versions to regenerate the dataset/hashes, and it produces the same files, the same size in the info, but different checksums (quite strange).
